spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/aws_project01_db?createDatabaseIfNotExist=true
    username: service01app
    password: 1234
  jpa:
    properties:
      hibernate.dialect: "org.hibernate.dialect.MySQL8Dialect"
    hibernate:
      ddl-auto: none